# Runs two docker linters
---
name: 'DockerLinting'
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      dockerfile_folder:
        type: 'string'
        default: '.'
        required: true
      hado_ignores:
        type: 'string'
        required: false
      action_ref:
        type: 'string'
        default: 'main'
        required: false
    secrets:
      ci_token:
        required: true

jobs:
  Hadolint:
    name: 'Hadolint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github-actions'
          ref: '${{ inputs.action_ref }}'

      - name: 'Run Hadolint'
        uses: './.github-actions/hadolint'
        env:
          GITHUB_TOKEN: '${{ secrets.ci_token }}'
          HADOLINT_ACTION_DOCKERFILE_FOLDER: '${{ inputs.dockerfile_folder }}'
          HADOLINT_ACTION_IGNORES: '${{ inputs.hado_ignores }}'
