# Runs cfn-lint and checkov
---
name: CfnLinting
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      checkov_skips:
        default: CKV_AWS_16,CKV_AWS_17,CKV_AWS_33,CKV_AWS_51,CKV_AWS_68,CKV_AWS_61
        type: string
        required: false
      cfn_files:
        required: true
        type: string
        default: '*cfn.yml'
      action_ref:
        default: 'main'
        type: string
        required: false
    secrets:
      ci_token:
        required: true

jobs:
  Cfnlint:
    name: cfn-lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout GitHub actions repo
        uses: actions/checkout@v2
        with:
          repository: novu/github-actions
          token: ${{ secrets.ci_token }}
          path: .github/actions
          ref: ${{ inputs.action_ref }}
      - name: Run cfn-lint
        uses: ./.github/actions/cfn-lint
        with:
          args: ${{ inputs.cfn_files }}

  Checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout GitHub actions repo
        uses: actions/checkout@v2
        with:
          repository: novu/github-actions
          token: ${{ secrets.ci_token }}
          path: .github/actions
          ref: ${{ inputs.action_ref }}
      - name: Run checkov
        uses: ./.github/actions/checkov
        with:
          skip_check: ${{ inputs.checkov_skips }}
          framework: cloudformation
        env:
          CKV_IGNORED_DIRECTORIES: mock-cfn
