name: "Terraform Apply for Monitor Rules"

on: 
  workflow_call:
    inputs:
      reset:
        type: string
        description: Reset Montiors (destroy & recreate)
        # this should be false. Do not change.  This flag is here to DRY workflows and is 
        # meant to be used by the manual-monitors.yaml workflow
        default: false
    secrets:
      DD_API_KEY:
        required: true
      DD_MONITOR_APP_KEY:
        required: true
      SUMOLOGIC_ACCESSID:
        required: true
      SUMOLOGIC_ACCESSKEY:
        required: true
      GHA_REPO_TOKEN:
        required: true
jobs:
  terraform:
    name: "Terraform Validation and Apply"
    runs-on:
      group: 'dhp-monitors'
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_MONITOR_APP_KEY }}
      SUMOLOGIC_ACCESSID: ${{ secrets.SUMOLOGIC_ACCESSID }}
      SUMOLOGIC_ACCESSKEY: ${{ secrets.SUMOLOGIC_ACCESSKEY }}
      SUMOLOGIC_ENVIRONMENT: 'us1'
    defaults:
      run:
        shell: bash
        # Terraform config directory
        working-directory: ./monitors

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Install Dependencies
        id: 'dependencies'
        run: |
          sudo apt update && sudo apt install -y nodejs git

      # https://github.com/hashicorp/setup-terraform/issues/96
      - name: Config Git
        id: 'config-git'
        run: |
          git config --global url."https://${{ secrets.GHA_REPO_TOKEN }}@github.com".insteadOf https://github.com

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0
      
      - name: Terraform init
        id: init
        run: terraform init
      
      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Destroy
        if: ${{ inputs.reset == 'true' }}
        id: destroy
        run: terraform destroy -auto-approve -input=false

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
