# Runs two docker linters
---
name: 'DockerLinting'
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      ecr_account_id:
        type: 'string'
        required: true
      dockerfile_folder:
        type: 'string'
        default: '.'
        required: true
      hado_ignores:
        type: 'string'
        required: false
      action_ref:
        type: 'string'
        default: 'main'
        required: false
      image_name:
        type: 'string'
        required: true
      image_tag:
        type: 'string'
        required: true
    secrets:
      ci_token:
        required: true
      twistlock_key_id:
        required: true
      twistlock_key:
        required: true
      aws_region:
        required: true
      aws_access_key_id:
        required: true
      aws_access_key:
        required: true

jobs:
  Hadolint:
    name: 'Hadolint'
    runs-on: 'tools'
    steps:
      - uses: 'actions/checkout@v2'

      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github-actions'
          ref: '${{ inputs.action_ref }}'

      - name: 'Run Hadolint'
        uses: './.github-actions/hadolint'
        env:
          GITHUB_TOKEN: '${{ secrets.ci_token }}'
          HADOLINT_ACTION_DOCKERFILE_FOLDER: '${{ inputs.dockerfile_folder }}'
          HADOLINT_ACTION_IGNORES: '${{ inputs.hado_ignores }}'

  # Twistlock_Scan:
  #   name: 'Twistlock Build and Scan for Vulnerabilities and Compliance'
  #   runs-on: 'ubuntu-latest'
  #   steps:
  #     - name: 'Checkout'
  #       uses: 'actions/checkout@v2'

  #     - name: 'Checkout GitHub actions repo'
  #       uses: 'actions/checkout@v2'
  #       with:
  #         repository: 'icariohealth/github-actions'
  #         token: '${{ secrets.ci_token }}'
  #         path: '.github-actions'
  #         ref: '${{ inputs.action_ref }}'

  #     - name: 'Configure AWS credentials'
  #       uses: 'aws-actions/configure-aws-credentials@v1'
  #       with:
  #         aws-access-key-id: '${{ secrets.aws_access_key_id }}'
  #         aws-secret-access-key: '${{ secrets.aws_access_key }}'
  #         aws-region: '${{ secrets.aws_region }}'

  #     - name: Run twistlock
  #       uses: ./.github-actions/twistlock
  #       env:
  #         AWS_REGION: '${{ secrets.aws_region }}'
  #       with:
  #         ecr_account_id: '${{ inputs.ecr_account_id }}'
  #         twistlock_key_id: '${{ secrets.twistlock_key_id }}'
  #         twistlock_key: '${{ secrets.twistlock_key }}'
  #         image_name: '${{ inputs.image_name }}'
  #         image_tag: '${{ inputs.image_tag }}'
