name: 'KustomizeLinting'
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      build_path:
        type: 'string'
        required: true
    secrets:
      ci_token:
        required: true

jobs:
  kustomize:
    name: 'kustomize'
    runs-on:
      group: 'tools-runner'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v4'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github-actions'
          ref: 'main'
      - name: 'Run kustomize'
        uses: './.github-actions/kustomize'
        with:
          build_path: '${{ inputs.build_path }}'
