# Runs several terraform linting tools

name: 'KustomizeLinting'
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      action_ref:
        default: 'main'
        type: 'string'
        required: false
    secrets:
      ci_token:
        required: true

jobs:
  kustomize:
    name: 'kustomize-dev'
    runs-on:
      group: 'tools-runner'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github-actions'
          ref: 'CLOUD-3258'
      - name: 'Run kustomize'
        uses: './.github-actions/kustomize'
        with:
          build_path: '${{ inputs.build_path }}'
