# Runs several terraform linting tools
---
name: 'TfLintingKustomize'
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      action_ref:
        default: 'main'
        type: 'string'
        required: false
    secrets:
      ci_token:
        required: true

jobs:
  terraform-fmt:
    name: 'terraform-fmt'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github/actions'
          ref: '${{ inputs.action_ref }}'
      - name: 'running terraform-fmt'
        uses: './.github/actions/terraform-fmt'

  tflint:
    name: 'tflint'
    runs-on: 'self-hosted'
    defaults:
      run:
        working-directory: ./infra/dev
    steps:
      - uses: 'actions/checkout@v2'
        name: 'Checkout GitHub actions repo'
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: 0.44.1
      - name: Run TFLint
        run: tflint -f compact --recursive

  tfsec:
    name: 'tfsec'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github/actions'
          ref: '${{ inputs.action_ref }}'
      - name: 'running tfsec'
        uses: './.github/actions/tfsec'

  kustomizeDev:
    name: 'kustomize-dev'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.NOVU_CI_TOKEN }}'
          path: '.github-actions'
          ref: 'main'
      - name: 'Run kustomize'
        uses: './.github-actions/kustomize'
        with:
          build_path: 'overlays/dev'

  kustomizeTst:
    name: 'kustomize-dev'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.NOVU_CI_TOKEN }}'
          path: '.github-actions'
          ref: 'main'
      - name: 'Run kustomize'
        uses: './.github-actions/kustomize'
        with:
          build_path: 'overlays/tst'

  kustomizestg:
    name: 'kustomize-stg'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.NOVU_CI_TOKEN }}'
          path: '.github-actions'
          ref: 'main'
      - name: 'Run kustomize'
        uses: './.github-actions/kustomize'
        with:
          build_path: 'overlays/stg'

  kustomizePrd:
    name: 'kustomize-prd'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.NOVU_CI_TOKEN }}'
          path: '.github-actions'
          ref: 'main'
      - name: 'Run kustomize'
        uses: './.github-actions/kustomize'
        with:
          build_path: 'overlays/prd'
