# Runs several terraform linting tools
---
name: TfLinting
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      action_ref:
        default: 'main'
        required: false
    secrets:
      ci_token:
        required: true

jobs:
  terraform-fmt:
    name: 'terraform-fmt'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github/actions'
          ref: ${{ inputs.action_ref }}
      - name: 'running terraform-fmt'
        uses: './.github/actions/terraform-fmt'

  tflint:
    name: 'tflint'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github/actions'
          ref: ${{ inputs.action_ref }}
      - name: 'running tflint'
        uses: './.github/actions/tflint'

  tfsec:
    name: 'tfsec'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github/actions'
          ref: ${{ inputs.action_ref }}
      - name: 'running tfsec'
        uses: './.github/actions/tfsec'