# Runs several terraform linting tools
---
name: 'TfLintingKustomize'
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      action_ref:
        default: 'main'
        type: 'string'
        required: false
    secrets:
      ci_token:
        required: true

jobs:
  terraform-fmt:
    name: 'terraform-fmt'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github/actions'
          ref: '${{ inputs.action_ref }}'
      - name: 'running terraform-fmt'
        uses: './.github/actions/terraform-fmt'

  tflint_dev:
    name: 'tflint-dev'
    runs-on: 'self-hosted'
    defaults:
      run:
        working-directory: ./infra/dev
    steps:
      - uses: 'actions/checkout@v2'
        name: 'Checkout GitHub actions repo'
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.39.3
      - name: Run TFLint
        run: tflint -f compact


  tflint_tst:
    name: 'tflint-tst'
    runs-on: 'self-hosted'
    defaults:
      run:
        working-directory: ./infra/tst
    steps:
      - uses: 'actions/checkout@v2'
        name: 'Checkout GitHub actions repo'
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.39.3
      - name: Run TFLint
        run: tflint -f compact

  tflint_stg:
    name: 'tflint-stg'
    runs-on: 'self-hosted'
    defaults:
      run:
        working-directory: ./infra/stg
    steps:
      - uses: 'actions/checkout@v2'
        name: 'Checkout GitHub actions repo'
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.39.3
      - name: Run TFLint
        run: tflint -f compact

  tflint_prd:
    name: 'tflint-prd'
    runs-on: 'self-hosted'
    defaults:
      run:
        working-directory: ./infra/prd
    steps:
      - uses: 'actions/checkout@v2'
        name: 'Checkout GitHub actions repo'
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.39.3
      - name: Run TFLint
        run: tflint -f compact

  tfsec:
    name: 'tfsec'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github/actions'
          ref: '${{ inputs.action_ref }}'
      - name: 'running tfsec'
        uses: './.github/actions/tfsec'
