# Runs several terraform linting tools
---
name: 'TfLinting'
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      action_ref:
        default: 'main'
        type: 'string'
        required: false
    secrets:
      ci_token:
        required: true

jobs:
  terraform-fmt:
    name: 'terraform-fmt'
    runs-on:
      group: 'tools-runner'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v4'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github/actions'
          ref: '${{ inputs.action_ref }}'
      - name: 'running terraform-fmt'
        uses: './.github/actions/terraform-fmt'

  tflint:
    name: 'tflint'
    runs-on:
      group: 'tools-runner'
    defaults:
      run:
        working-directory: .
    steps:
      - uses: 'actions/checkout@v4'
        name: 'Checkout GitHub actions repo'
      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.48.0
      - name: Run TFLint
        run: tflint -f compact --recursive

  tfsec:
    name: 'tfsec'
    runs-on:
      group: 'tools-runner'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v4'
        with:
          repository: 'icariohealth/github-actions'
          token: '${{ secrets.ci_token }}'
          path: '.github/actions'
          ref: '${{ inputs.action_ref }}'
      - name: 'running tfsec'
        uses: './.github/actions/tfsec'
